### ISSUE TITLE
Don't break running configurations of other software

### ISSUE THREAD

**Issue by tbe** [openpetra/getopenpetra#3]
The install script can destroy already running systems, without notifying the user about the dangers.

- It edits the nginx default site
- it edits the nginx _global_ fastcgi parameters
- it edits the global php-fpm configuration

If some unexperienced admin/user, as you find them often in small non-profit organisations, runs this script on a production server, this would result in downtime and a lot of confusion.

At least this behavior should be well documented, if not avoided at all ( only create custom configs, never alter system configs).

**Comment by tpokorra** [comment]
One solution would be to fail the script at the beginning, if there is an existing nginx configuration.

This script should be run on a fresh container or VM. This script is only for testing purposes.
Small charities with unexperienced admin should not run such a server themselves.

Pull requests are welcome.

**Comment by tbe** [comment]
> This script should be run on a fresh container or VM. This script is only for testing purposes.
> Small charities with unexperienced admin should not run such a server themselves.

In this case, the text on https://www.openpetra.org/download-openpetraorg should be fixed ;) 
> You can also install OpenPetra locally or on your own server, have a look at this script: https://get.openpetra.org

> Pull requests are welcome.

I'm working on a PR on the main project for a docker image as easy install solution. I don't like shell install scripts ;)

**Comment by tpokorra** [comment]
You are right. I have updated the text on https://www.openpetra.org/download-openpetraorg, and I have adjusted the script.

I am looking forward to seeing your docker image and script.
I have done some work with docker before, but did not see a need for it for OpenPetra yet.
