### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by knobi4711** [openpetra/getopenpetra#4]
No matter if I try the installation on a bare Ubuntu 22 or Debian 11, no matter if as root or with sudo, the script always aborts the installation.
![fail](https://github.com/openpetra/getopenpetra/assets/37896432/f0443906-0615-4ce9-b5cc-44770c2f1f0e)

**Comment by tpokorra** [comment]
@knobi4711 
You are right. That won't work.

I was asked to put in this check, because someone run the script on a production server and destroyed it with that script.

Try this:

```
curl https://get.openpetra.org | bash -s devenv --iknowwhatiamdoing=yes
```

**Comment by tpokorra** [comment]
@knobi4711 
Thank you for reporting this. I have fixed the script.
