### ISSUE TITLE
BUILD FAILED - installation via curl doesn't work

### ISSUE THREAD

**Issue by Myronised** [openpetra/getopenpetra#5]
I'd like to install openpetra on my Ubuntu 20.04 VM Server (Hetzner Hosting). But when I execute the command curl https://get.openpetra.org | bash -s devenv --iknowwhatiamdoing=yes, after a while, I always get this error message (already tried it on Ubuntu 18-22 & CentOS):

`NAnt 0.92 (Build 0.92.4526.0; rc1; 5/23/2012)
Copyright (C) 2001-2012 Gerry Shaw
http://nant.sourceforge.net

Buildfile: file:///home/op_dev/openpetra/OpenPetra.build
Target framework: Mono 4.5 Profile
Target(s) specified: install.js 

     [echo] operating system=Unix 5.4.0.177
     [echo] platform=unix
  [include] Including file /home/op_dev/openpetra/OpenPetra.build.config.
     [echo] Running on Unix

install.js:

     [exec] npm warn deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
     [exec] npm warn deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
     [exec] npm warn deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
     [exec] npm warn deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
     [exec] npm warn deprecated i18next-xhr-backend@1.5.1: replaced by i18next-http-backend
     [exec] npm warn deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
     [exec] 
     [exec] added 356 packages, and audited 357 packages in 24s
     [exec] 
     [exec] 54 packages are looking for funding
     [exec]   run `npm fund` for details
     [exec] 
     [exec] 1 high severity vulnerability
     [exec] 
     [exec] To address all issues, run:
     [exec]   npm audit fix
     [exec] 
     [exec] Run `npm audit` for details.
     [exec] 
     [exec] > openpetra-client-js@2018.2.0 build
     [exec] > npm run build-debug && npm run build-min
     [exec] 
     [exec] 
     [exec] > openpetra-client-js@2018.2.0 build-debug
     [exec] > mkdir -p dist && mkdir -p webfonts && cp -f node_modules/\@fortawesome/fontawesome-free/css/all.min.css dist/fontawesome.min.css && cp -f node_modules/\@fortawesome/fontawesome-free/webfonts/* webfonts && browserify -t browserify-css src/index.js -d > dist/bundle.js && chmod a+rx -R dist webfonts
     [exec] 
     [exec] 
     [exec] /home/op_dev/openpetra/js-client/node_modules/axios/index.js:1
     [exec] import axios from './lib/axios.js';
     [exec] ^
     [exec] ParseError: 'import' and 'export' may appear only with 'sourceType: module'

BUILD FAILED - 0 non-fatal error(s), 11 warning(s)

External Program Failed: bash (return code was 1)

Total time: 27.1 seconds.`

I can't get it working. What's the problem?

**Comment by tpokorra** [comment]
@Myronised 
Thanks for looking into OpenPetra.
yes, the test branch was broken by myself, when I tried to upgrade the javascript libraries.
I have now reverted the problematic commit (https://github.com/openpetra/openpetra/commit/8851aaa42b918eedff53fb186fc39d45927b1c38), and it works again for me.
Please try again.
